micronaut:
  application:
    name: micronautRest

mongodb:
#  uri: mongodb://username:password@localhost:27017/users
  uri: mongodb://${MONGO_HOST:@localhost}:${MONGO_PORT:27017}/users
  cluster:
    maxWaitQueueSize:5
  connectionPool:
    maxSize:20
